# This is a basic workflow to help you get started with Actions

name: payments-tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    env:
      STRIPE_KEY: 'sk_test_51K9coBE0iPUH1rrhQQubGSkAcDCE2BJPMPFGPUuBSTDKVaBJi6jbOFN2YMwi3InLNE7R2sJnSEop1wLAySG5TmEQ00DvFd09Pq'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - run: cd payments && npm install && npm run test:ci
